### ISSUE TITLE
Documentation of extract_subpopulations is not up-to-date

### ISSUE THREAD

**Issue by cells2numbers** [shntnu/pertminr#112]
The documentation of extract_subpopulations says

```{r}
extract_subpopulations extracts the clusters enriched/de-enriched in a given set w.r.t a reference set. 
```

Actually, the cluster centers are calculated using data points from the reference and the population data frame.

**Comment by shntnu** [comment]
How is this?

@cells2numbers @mrohban 
  
    #' \code{extract_subpopulations} extracts clusters from population and reference sets 
    #' and reports the frequency of points in each cluster for the sets

**Comment by cells2numbers** [comment]
That is actually what it is doing :)

**Comment by shntnu** [comment]
#113
