### ISSUE TITLE
Implement random projections for covariance profiling

### ISSUE THREAD

**Issue by shntnu** [shntnu/pertminr#115]
@mrohban I removed the random projections part in covariance profiling #114. 

I wondering whether we should have random projections as a separate feature transformation step? That's because if you have say, just 10 variables, it may be ok to have 45 covariance features. 

The disadvantage of that approach is that for larger feature sets, the dataframe can get too wide, take up memory, making it a pain to do random projections later. 

One mitigant for this is to do [sparse random projections](http://scikit-learn.org/stable/modules/random_projection.html#sparse-random-projection), which will be faster.

What do you think?

**Comment by mrohban** [comment]
I think we can try out the sparse random projection and benchmark it on some datasets to see how it works.
