### ISSUE TITLE
Aggregate function

### ISSUE THREAD

**Issue by PeterLu0403** [shntnu/pertminr#134]
Hi,

The function of the aggregate may need an update due to the new version of dplyr package.
Now the naming is features_fn1...features_fn2... which should be features_median...features_mad... e.g.
possible solution:

`dplyr::group_by_(.dots = strata) %>%
  dplyr::summarise_at(tibble::lst(aggregating_function), .vars = variables) %>%
  dplyr::ungroup() `

Cheers,
Peter Lu

**Comment by shntnu** [comment]
Thanks @PeterLu0403 
Would you be willing to test that out and make a PR?

**Comment by PeterLu0403** [comment]
@shntnu 
Hi, 

This issue was fixed by the update of the dplyr package(0.8.3). 

Cheers,
Peter Lu

**Comment by shntnu** [comment]
Fixed in #135
