### ISSUE TITLE
Decide on data structure for tracking datasets

### ISSUE THREAD

**Issue by shntnu** [shntnu/pertminr#40]
@cells2numbers said:

I am implementing a simple csv export for my Matlab tracking software and I am looking for your advice 
The csv is meant for importing into cytominer. Are there any conventions / restrictions for the csv I should know about? 

In general, I use the following hierarchy / data structure:
1. 2D info. In each frame I have an image segmentation and each cell is described by its morphology (are, position, length, mean intensity etc)
2. 2D + t info. After cell tracking each neutrophil (cell) is represented as a trajectory. This trajectory is described using spatiotemporal information (displacement, velocity, length of the trajectory in frames, randomness of movement etc.). 
3. Experiment Info. Each experiment is described using the mean values of the spatiotemporal information. Additional parameters like the x- and y-FMI (forward migration index) are calculated; these parameters describe for example the portion of cells moving towards a specific site / chemoattractant. 

To have a flexible implementation, I plan to export the 2D information of the cells per frame. For each cell, the corresponding trajectory id is stored as well ->  this allows to easily calculate features like velocity etc. in cytominer and should allow to easily import other file formats / data. 

Using this setup, the image segmentation and tracking performed using Matlab or CellProfiler is independent from the analysis in cytominer. I only need a good and flexible way to store the tracking data in R.

**Comment by AnneCarpenter** [comment]
I can't answer your question but I would suggest considering the format CellProfiler exports as the type/style that should feed into cytominer?

**Comment by shntnu** [comment]
@cells2numbers: 
For the data structure – it's best to stick with a data frame, and indeed a CSV would be the way to go for that. 

Regarding the structure of the CSV: please use whatever ExportToSpreadsheet outputs. Although cytominer makes no assumptions about the column names, it is good to stay consistent with CellProfiler output. This means that for 2D info, there will be columns names `ImageNumber` `ObjectNumber`, `Cells_Parent_Nuclei` (or some such column) and `Metadata_*`.

`2D+t` info can then be obtained from `2D` using a cytominer / dplyr verb (which you need to implement)
Similarly, `Experiment` can be obtained from `2D+t` using a cytominer / dplyr verb (probably `cytominer::summarize`).

Thus you wouldn't need separate data structure for those two (`2D+t` and `Experiment` will also be data frames). You can always save them explicitly as a separate step.

The cytominer verbs yet to be implemented of course. 

We need to name them first! :) How about

`track` : `2D` -> `2D+t`  

and I think the existing `dplyr::summarize` would suffice for `2D+t` -> `Experiment`

**Comment by cells2numbers** [comment]
I agree, it is a good idea to use consistent output / variables in MATLAB and CellProfiler (until I get rid of Matlab ;) I implemented an export to csv that uses the same data structure as CellProfiler (based on the output of Track Objects and ExportToSpreadsheet). 

To compare MATLAB and CP experiments I used a simple artificial image sequence (attached gif, I should call it atari data ;) . The results of tracking this data using MATLAB or CellProfiler are stored as [csv files](https://github.com/broadinstitute/2017_03_08_neutrophile_migration_becker/tree/master/analysis/testsequence) that can directly be compared.  I recognized that the tracks in CellProfiler are stored as "TrackObjects_Label_50". I think the additional "_50" describes a parameter used during tracking (this would allow to store several tracking results).  

Regarding R: To import the tracks into R I use the nest function of tidyr
 
```{r }
tracksCP <- read.csv('../analysis/testsequence/2017_03_test_sequence_cellprofiler.csv') %>% print()

tracksCP_nested <-
  tracksCP %>%
  nest(-TrackObjects_Label_50) %>%
  print()
```

Next step: create appropriate data structures using a dplyr verb :) 

@shntnu for the names I would prefer trajectories :) Can you point me to a good starting point for the cytominer / dplyer implementation?

 
Here is my atari sequence :) 

![test_sequence](https://cloud.githubusercontent.com/assets/21295504/24532196/88eb2b58-158c-11e7-8c31-3567bbab0032.gif)

**Comment by shntnu** [comment]
Cool - your starting point would be to create the function / verb `trajectory` (although see if you can come up with an equivalent verb) that reads a data.frame like `tracks` and outputs the spatiotemporal information of each track.

For the next step, I think this would suffice
```
tracks %>% 
  cytominer::trajectory() %>%
  dplyr::group_by(TrackObjects_Label_50) %>%
  dplyr::summarize_at(.cols = list_of_spatiotemporal_columns, .funs = mean)
```

If you need other summaries beyond the mean for each, then considering doing something like this http://stackoverflow.com/a/36822724

**Comment by cells2numbers** [comment]
data structures and features for time lapse data will not be included into cytominer but is moved to its own package https://github.com/cells2numbers/neutrominer
