### ISSUE TITLE
Implement Similarity network fusion 

### ISSUE THREAD

**Issue by shntnu** [shntnu/pertminr#49]
http://www.nature.com/nmeth/journal/v11/n3/full/nmeth.2810.html

**Comment by cells2numbers** [comment]
I tested and used the implementation from Max Conway

https://github.com/maxconway/SNFtool/blob/master/R/SNF.R 

Could it be added as an dependency?

**Comment by shntnu** [comment]
@cells2numbers sounds good! But have a look at http://r-pkgs.had.co.nz/description.html#dependencies to decide the level of the dependency.

**Comment by cells2numbers** [comment]
example vignette showing the usage of SNF can be found in cytominergallery, see https://github.com/cytomining/cytominergallery/pull/43

**Comment by shntnu** [comment]
Will track in cytomining/cytominergallery#43
