### ISSUE TITLE
Non-standard evaluation (NSE) in dplyr in drop_na_rows

### ISSUE THREAD

**Issue by mrohban** [shntnu/pertminr#73]
`devtools` gives following note in checking R code for possible problems:

`* checking R code for possible problems ... NOTE
drop_na_rows: no visible binding for global variable ‘value’
drop_na_rows: no visible binding for global variable ‘key’
drop_na_rows: no visible binding for global variable ‘rowname_temp’
Undefined global functions or variables:
  key rowname_temp value`

We can get rid of it simply by using NSE operations in dplyr.

**Comment by shntnu** [comment]
That's odd - it should have been fixed in https://github.com/cytomining/cytominer/blob/3d48e57082e3036253b0f5d28b50b80189aab66c/R/drop_na_rows.R

@mrohban Do you have the latest master?

**Comment by mrohban** [comment]
Never mind, my master was not updated.
